# Generated by Django 4.2.6 on 2023-10-17 20:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nombre del proyecto')),
                ('slug', models.SlugField(max_length=250, unique=True, unique_for_date='published', verbose_name='Slug')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen de proyecto')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10, verbose_name='Estado del post')),
                ('github', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Link al proyecto en git')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portfolio.category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
