# Generated by Django 4.2.6 on 2023-10-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, unique_for_date='published', verbose_name='Slug'),
        ),
    ]
